travis:
  secure:
    BINSTAR_TOKEN: QVUWt2FqPfmEXcGlI087edas8REWq18/+Kmc3W5ww9h/li48LRXbJCSU2zDMymJnv58JJKMRvv7DM1l8p+oa/TtQc2eoMpuFar8U3tvvurG2wG119TZX/dA1maXXMMpoPllcqHefhk3bJd8vFtMLzjzv06jbIpjONOs2faMpHsSCWPGZ5ScbrCiWAAaSdL8pqqlJnC+2RWhPNJzmHyX/0B53fci+3euSrpkgm+hCJrf9To62+tT+P5iqRENnBv+mcpLAibY0HJccCfKAPLUDzim/yY5xQaQBQ4ntmrrJRRNehHRWJXLUDQGcqpPE1Q2lCo3OBgAICfC2Gf4xvehO+4JPCMTgufNNSQ4DtW5zL4IpPA8BTKMcfVwCWmM9wH1YmQB465jr+c/Fwt9uMynPm9eLaCUwNtokuEwNtvPeDEzoNimjVDEsDUsDkkGeuJYsaZOi5Hj448zfDXu9GxMVWr6MNiIiAA5WmN7mCp0K+CfA3+sceLRWdgkEojcDsyszRV+vY8ehnQmQCj5ieDTl7Rz9oxOpZoqQuLEhTNRHOTiDDx478Tiffn00jb7htep0c+qQEpmLzYeBdzKxzXLQUbDUhRKhcZlbQkQGQmV5tpj9p8Btd26AoBpIP9lNIxyEFbkUBblFe5cGJsU07METgsAbrAd+Qdm10ECxFuSRcHo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
