travis:
  secure:
    BINSTAR_TOKEN: GEGquiNx8vFlK5LAHfIneLFFITjFrVmwu6KY3qQ6juCAmKYKjMizK2Gv86KPjzMNOWiAUf/76jz8ZNt+E5XcXBtQRptvyASj0PCRjp3Zrxz3yVtj9s8ojUqmJUnoxdHgRJijCVaLfoQuzkecHNGBrHQ5ymRfzWpI0qmEiKrl9bejCj1SNje7M8DNScyw+Rx2bNmZyrkrkKn5APNPGnBvWxM6PLyz/RWo2z6J+xrZWO3QOtgzj4lGHpUwmsgflwWi321wRq2wvqEzRxmPzbgK8h0pkieKFBLj8kDkpBWvEMqrEoyWOITi4fOlQeiqzZaV58+AysAsoe0ggmhomYCHaUonNgf6IeEJAaSMONjFbNvlvHtpvHQJ1d8XGz5RtxAmrAdtzXc3NIE18Q7QB/moo4OdwI4+DwtWW2tnO5rXjeyaiVoDtOhoNhGaECCtbTLb9+QFLglcNM/1drJ5gOXMsZ5NLn6gjLoSOIbXRC4I7MjGWvrCSStvJK7tffQBYMvER0IimuR5AwDo9zVsAy45o4KKDZ2jbIH07iV+qRahtjjC+80t7Q5eIViyi2ASg/FBxQss2cyyBue2THqOpKCaGfMNaXGzXYCtfgl+1ocKdwgv1M50y2aXKcaFKJaiWnVAIn1xev4/XEjPa7Uzi6r81C3jZK6HsWiaK4TpeBixqUM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
